server {
    listen 80;
    root /var/www/html;
    index index.php;

    error_page 404 /404.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
        # Intercept errors from PHP-FPM and display custom error pages
        fastcgi_intercept_errors on;
    }

    # Block direct access to sensitive files
    location ~/\.(git|env) {
        deny all;
    }
}